=== nancypapu/xml/Tracker/feedback.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Tracker (feedback)+>
<!ATTLIST Tracker
  xmlns CDATA #FIXED ''>

<!ELEMENT feedback (name,phone,email,feed,age)>
<!ATTLIST feedback
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone
  xmlns CDATA #FIXED ''>

<!ELEMENT email (#PCDATA)>
<!ATTLIST email
  xmlns CDATA #FIXED ''>

<!ELEMENT feed (#PCDATA)>
<!ATTLIST feed
  xmlns CDATA #FIXED ''>

<!ELEMENT age (#PCDATA)>
<!ATTLIST age
  xmlns CDATA #FIXED ''>

=== nancypapu/xml/Tracker/feedback.xml
<?xml version="1.0" encoding = "UTF-8"?>
<!--<!DOCTYPE Tracker SYSTEM "feedback.dtd">-->
<?xml-stylesheet type="text/xsl" href="tracker.xsl" ?>

<Tracker>

<feedback>
<name>jaanu</name>
<phone>8765432134</phone>
<email>jaanuram96@gmail.com</email>
<feedback>The website helps me to find out the daily cases details which is very helpful</feedback>
<age>20</age>
</feedback>


<feedback>
<name>vidhya</name>
<phone>8776432134</phone>
<email>vidhyavox@gmail.com</email>
<feedback>The website enables the user to understand and interact in an effective way</feedback>
<age>20</age>
</feedback>


<feedback>
<name>mariya</name>
<phone>7687546633</phone>
<email>mariyajoseph@gmail.com</email>
<feedback>Covid chatbot is quite interesting and appealing</feedback>
<age>20</age>
</feedback>


<feedback>
<name>anu</name>
<phone>9876432134</phone>
<email>anumandu@gmail.com</email>
<feedback>Quiz in this website helps us to gain knowledge about covid </feedback>
<age>20</age>
</feedback>


<feedback>
<name>samyuktha</name>
<phone>6565473724</phone>
<email>samyukthacool@gmail.com</email>
<feedback>The user interface is very user friendly and easy to use and navigate.</feedback>
<age>20</age>
</feedback>

</Tracker>
